//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Resources.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Template.Resources.Content.Titles", typeof(Titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string AccountLogin {
            get {
                return ResourceManager.GetString("AccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role creation.
        /// </summary>
        public static string AdministrationRolesCreate {
            get {
                return ResourceManager.GetString("AdministrationRolesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role deletion.
        /// </summary>
        public static string AdministrationRolesDelete {
            get {
                return ResourceManager.GetString("AdministrationRolesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role details.
        /// </summary>
        public static string AdministrationRolesDetails {
            get {
                return ResourceManager.GetString("AdministrationRolesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role edit.
        /// </summary>
        public static string AdministrationRolesEdit {
            get {
                return ResourceManager.GetString("AdministrationRolesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string AdministrationRolesIndex {
            get {
                return ResourceManager.GetString("AdministrationRolesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User creation.
        /// </summary>
        public static string AdministrationUsersCreate {
            get {
                return ResourceManager.GetString("AdministrationUsersCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deletion.
        /// </summary>
        public static string AdministrationUsersDelete {
            get {
                return ResourceManager.GetString("AdministrationUsersDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details.
        /// </summary>
        public static string AdministrationUsersDetails {
            get {
                return ResourceManager.GetString("AdministrationUsersDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User edit.
        /// </summary>
        public static string AdministrationUsersEdit {
            get {
                return ResourceManager.GetString("AdministrationUsersEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string AdministrationUsersIndex {
            get {
                return ResourceManager.GetString("AdministrationUsersIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System error.
        /// </summary>
        public static string HomeError {
            get {
                return ResourceManager.GetString("HomeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeIndex {
            get {
                return ResourceManager.GetString("HomeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string HomeNotFound {
            get {
                return ResourceManager.GetString("HomeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string HomeUnauthorized {
            get {
                return ResourceManager.GetString("HomeUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile deletion.
        /// </summary>
        public static string ProfileDelete {
            get {
                return ResourceManager.GetString("ProfileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile details.
        /// </summary>
        public static string ProfileDetails {
            get {
                return ResourceManager.GetString("ProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile edit.
        /// </summary>
        public static string ProfileEdit {
            get {
                return ResourceManager.GetString("ProfileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileIndex {
            get {
                return ResourceManager.GetString("ProfileIndex", resourceCulture);
            }
        }
    }
}
